import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb, PDFName, PDFArray, PDFString } from "pdf-lib";

export const runtime = "nodejs";

type Slide = {
  title: string;
  bullets: string[];
  content?: string | null;
  image?: string | null;
  imageCredit?: string | null;
  youtubeVideoId?: string | null;
};

async function fetchBytes(url: string): Promise<Uint8Array> {
  if (url.startsWith("data:")) {
    const base64 = url.split(",")[1] ?? "";
    return Buffer.from(base64, "base64");
  }
  const r = await fetch(url);
  if (!r.ok) throw new Error(`Failed to fetch: ${r.status}`);
  return new Uint8Array(await r.arrayBuffer());
}

/** Replace characters outside WinAnsi range so pdf-lib Helvetica doesn't throw. */
function sanitize(text: string): string {
  return text
    .replace(/[\u2018\u2019\u201A\u201B]/g, "'")   // curly single quotes
    .replace(/[\u201C\u201D\u201E\u201F]/g, '"')    // curly double quotes
    .replace(/\u2013/g, "-")                        // en dash
    .replace(/\u2014/g, "--")                       // em dash
    .replace(/\u2026/g, "...")                      // ellipsis
    .replace(/\u2022/g, "*")                        // bullet
    .replace(/\u00A0/g, " ")                        // non-breaking space
    .replace(/[^\x00-\xFF]/g, "?");                 // any remaining non-latin
}

function wrapText(text: string, maxChars: number) {
  const words = text.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (test.length > maxChars) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}

// Design tokens
const NAVY   = rgb(0.086, 0.396, 0.204);  // green-800 #166534
const BLUE   = rgb(0.086, 0.639, 0.290);  // green-500 #16a34a
const WHITE  = rgb(1, 1, 1);
const DARK   = rgb(0.08, 0.08, 0.13);
const MID    = rgb(0.42, 0.42, 0.48);
const LIGHT  = rgb(0.96, 0.97, 0.99);
const RULE   = rgb(0.88, 0.90, 0.94);

export async function POST(req: Request) {
  try {
    const { deckTitle = "Lesson", slides } = (await req.json()) as {
      deckTitle?: string;
      slides: Slide[];
    };

    if (!slides?.length) {
      return NextResponse.json({ error: "slides required" }, { status: 400 });
    }

    const pageW = 960;
    const pageH = 540;
    const HEADER_H = 80;

    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

    // ── Title page ────────────────────────────────────────────────
    {
      const page = pdf.addPage([pageW, pageH]);

      // Full navy background
      page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: NAVY });

      // Accent stripe — left edge
      page.drawRectangle({ x: 0, y: 0, width: 10, height: pageH, color: BLUE });

      // Deck title — centered vertically
      const titleSize = 44;
      const titleY = pageH / 2 + 20;
      page.drawText(sanitize(deckTitle), {
        x: 72,
        y: titleY,
        size: titleSize,
        font: fontBold,
        color: WHITE,
      });

      page.drawText("Generated by AI  ·  Cipher", {
        x: 72,
        y: titleY - 52,
        size: 16,
        font,
        color: rgb(0.6, 0.85, 0.65),
      });
    }

    // ── Content slides ─────────────────────────────────────────────
    for (const s of slides) {
      const page = pdf.addPage([pageW, pageH]);

      // White background
      page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: WHITE });

      // Header band
      page.drawRectangle({ x: 0, y: pageH - HEADER_H, width: pageW, height: HEADER_H, color: NAVY });

      // Left accent stripe on header
      page.drawRectangle({ x: 0, y: pageH - HEADER_H, width: 6, height: HEADER_H, color: BLUE });

      // Title in header
      const title = sanitize(s.title ?? "");
      page.drawText(title, {
        x: 36,
        y: pageH - HEADER_H + 26,
        size: 26,
        font: fontBold,
        color: WHITE,
        maxWidth: 860,
      });

      // Layout: image/video on right if present, else full-width text
      const hasImage = Boolean(s.image);
      const hasYouTube = !hasImage && Boolean(s.youtubeVideoId);
      const hasVisual = hasImage || hasYouTube;

      const contentTop = pageH - HEADER_H - 16;  // y just below header
      const contentBottom = 44;                   // above footer
      const contentH = contentTop - contentBottom;

      const textX = 36;
      const textW = hasVisual ? 498 : 880;
      const bulletSize = 18;
      const lineH = 26;
      const bulletIndent = 28;

      if (s.content) {
        // Upper grades: render as wrapped paragraph
        const maxChars = hasVisual ? 66 : 130;
        const lines = wrapText(sanitize(s.content), maxChars);
        const totalH = lines.length * lineH;
        let cursorY = contentBottom + Math.floor((contentH + totalH) / 2);
        for (const line of lines) {
          if (cursorY < contentBottom + 10) break;
          page.drawText(line, {
            x: textX,
            y: cursorY,
            size: bulletSize,
            font,
            color: DARK,
            maxWidth: textW,
          });
          cursorY -= lineH;
        }
      } else {
        // Primary grades: render as bullet list
        let totalBulletsH = 0;
        for (const b of s.bullets || []) {
          const maxChars = hasVisual ? 44 : 90;
          const lines = wrapText(sanitize(b), maxChars);
          totalBulletsH += lines.length * lineH + 10;
        }
        if (totalBulletsH > 0) totalBulletsH -= 10;

        let cursorY = contentBottom + Math.floor((contentH + totalBulletsH) / 2);

        for (const b of s.bullets || []) {
          const maxChars = hasVisual ? 44 : 90;
          const lines = wrapText(sanitize(b), maxChars);

          page.drawEllipse({
            x: textX + 10,
            y: cursorY + bulletSize * 0.35,
            xScale: 4,
            yScale: 4,
            color: BLUE,
          });

          let lineY = cursorY;
          for (const line of lines) {
            page.drawText(line, {
              x: textX + bulletIndent,
              y: lineY,
              size: bulletSize,
              font,
              color: DARK,
            });
            lineY -= lineH;
          }

          cursorY = lineY - 10;
          if (cursorY < contentBottom + 10) break;
        }
      }

      // ── Image column ──────────────────────────────────────────────
      if (hasImage) {
        const imgX = 556;
        const imgW = 368;
        const imgH = contentH - 4;
        const imgY = contentBottom + 2;

        // Rounded-corner background card
        page.drawRectangle({
          x: imgX,
          y: imgY,
          width: imgW,
          height: imgH,
          color: LIGHT,
          borderColor: RULE,
          borderWidth: 1,
        });

        if (s.image) {
          try {
            const bytes = await fetchBytes(s.image);
            let embedded;
            try { embedded = await pdf.embedJpg(bytes); }
            catch { embedded = await pdf.embedPng(bytes); }

            const dims = embedded.scale(1);
            // "contain" fit — image stays inside the box
            const scale = Math.min((imgW - 8) / dims.width, (imgH - 8) / dims.height);
            const drawW = dims.width * scale;
            const drawH = dims.height * scale;
            const dx = imgX + (imgW - drawW) / 2;
            const dy = imgY + (imgH - drawH) / 2;

            page.drawImage(embedded, { x: dx, y: dy, width: drawW, height: drawH });
          } catch {
            // image fetch failed — show nothing (box already drawn)
          }
        }

        if (s.imageCredit) {
          page.drawText(sanitize(s.imageCredit).slice(0, 55), {
            x: imgX + 4,
            y: imgY - 14,
            size: 7.5,
            font,
            color: MID,
          });
        }
      }

      // ── YouTube column ─────────────────────────────────────────────
      if (hasYouTube && s.youtubeVideoId) {
        const videoId = s.youtubeVideoId;
        const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
        const shortUrl = `youtu.be/${videoId}`;

        const boxX = 556;
        const boxW = 368;
        const boxH = contentH - 4;
        const boxY = contentBottom + 2;

        // Card background
        page.drawRectangle({
          x: boxX, y: boxY, width: boxW, height: boxH,
          color: LIGHT, borderColor: RULE, borderWidth: 1,
        });

        // YouTube red play button icon (circle + triangle)
        const cx = boxX + boxW / 2;
        const cy = boxY + boxH / 2 + 20;
        const r = 28;
        page.drawEllipse({ x: cx, y: cy, xScale: r, yScale: r, color: rgb(0.86, 0.08, 0.08) });
        page.drawSvgPath("M -9 -13 L 15 0 L -9 13 Z", { x: cx, y: cy, color: WHITE });

        // "YouTube" label
        page.drawText("YouTube", {
          x: cx - 32,
          y: cy - r - 18,
          size: 13,
          font: fontBold,
          color: rgb(0.86, 0.08, 0.08),
        });

        // Short URL text
        page.drawText(shortUrl, {
          x: boxX + (boxW - shortUrl.length * 6.5) / 2,
          y: cy - r - 38,
          size: 11,
          font,
          color: MID,
        });

        // Clickable link annotation over the whole card
        const linkAnnot = pdf.context.obj({
          Type: "Annot",
          Subtype: "Link",
          Rect: [boxX, boxY, boxX + boxW, boxY + boxH],
          Border: [0, 0, 0],
          C: [],
          A: { Type: "Action", S: "URI", URI: PDFString.of(videoUrl) },
        });
        const linkRef = pdf.context.register(linkAnnot);

        const existing = page.node.lookup(PDFName.of("Annots"));
        if (existing instanceof PDFArray) {
          existing.push(linkRef);
        } else {
          page.node.set(PDFName.of("Annots"), pdf.context.obj([linkRef]));
        }
      }

      // ── Footer ────────────────────────────────────────────────────
      page.drawLine({
        start: { x: 36, y: 38 },
        end:   { x: pageW - 36, y: 38 },
        thickness: 0.5,
        color: RULE,
      });
      page.drawText("Cipher", {
        x: 36,
        y: 22,
        size: 10,
        font,
        color: MID,
      });
    }

    const bytes = await pdf.save();
    const filename =
      (deckTitle || "lesson").replace(/[^a-z0-9-_ ]/gi, "").trim().replace(/\s+/g, "_") + ".pdf";

    return new NextResponse(Buffer.from(bytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: "export pdf failed", details: String(err?.message ?? err) },
      { status: 500 }
    );
  }
}
