import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export const runtime = "nodejs";

type Slide = {
  title: string;
  bullets: string[];
  image?: string | null; // URL
};

async function fetchBytes(url: string): Promise<Uint8Array> {
  const r = await fetch(url);
  if (!r.ok) throw new Error(`Failed to fetch: ${r.status}`);
  return new Uint8Array(await r.arrayBuffer());
}

function wrapText(text: string, maxChars: number) {
  const words = text.split(" ");
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const test = line ? `${line} ${w}` : w;
    if (test.length > maxChars) {
      if (line) lines.push(line);
      line = w;
    } else {
      line = test;
    }
  }
  if (line) lines.push(line);
  return lines;
}

export async function POST(req: Request) {
  try {
    const { deckTitle = "Lesson", slides } = (await req.json()) as {
      deckTitle?: string;
      slides: Slide[];
    };

    if (!slides?.length) {
      return NextResponse.json({ error: "slides required" }, { status: 400 });
    }

    // 16:9 page size similar to widescreen slides
    const pageW = 960;
    const pageH = 540;

    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

    // Title page
    {
      const page = pdf.addPage([pageW, pageH]);
      page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });

      page.drawText(deckTitle, {
        x: 60,
        y: pageH / 2 + 10,
        size: 40,
        font: fontBold,
        color: rgb(0.07, 0.09, 0.13),
      });
      page.drawText("Generated by AI", {
        x: 60,
        y: pageH / 2 - 30,
        size: 16,
        font,
        color: rgb(0.4, 0.4, 0.45),
      });
    }

    for (const s of slides) {
      const page = pdf.addPage([pageW, pageH]);
      page.drawRectangle({ x: 0, y: 0, width: pageW, height: pageH, color: rgb(1, 1, 1) });

      // Title
      const title = s.title ?? "";
      page.drawText(title, {
        x: 48,
        y: pageH - 70,
        size: 28,
        font: fontBold,
        color: rgb(0.07, 0.09, 0.13),
      });

      // Left text box
      const leftX = 48;
      const leftYTop = pageH - 115;
      const leftW = 520;

      // light panel
      page.drawRectangle({
        x: leftX,
        y: 70,
        width: leftW,
        height: pageH - 200,
        color: rgb(0.97, 0.97, 0.98),
        borderColor: rgb(0.9, 0.9, 0.92),
        borderWidth: 1,
      });

      let cursorY = leftYTop;
      const bulletSize = 18;

      for (const b of s.bullets || []) {
        const lines = wrapText(b, 38);
        // bullet dot
        page.drawText("•", {
          x: leftX + 18,
          y: cursorY,
          size: bulletSize,
          font: fontBold,
          color: rgb(0.07, 0.09, 0.13),
        });

        // text lines
        let lineY = cursorY;
        for (const line of lines) {
          page.drawText(line, {
            x: leftX + 42,
            y: lineY,
            size: bulletSize,
            font,
            color: rgb(0.07, 0.09, 0.13),
          });
          lineY -= 22;
        }

        cursorY = lineY - 8;
        if (cursorY < 110) break;
      }

      // Right image box
      const imgX = 600;
      const imgY = 110;
      const imgW = 312;
      const imgH = 330;

      // image frame
      page.drawRectangle({
        x: imgX,
        y: imgY,
        width: imgW,
        height: imgH,
        color: rgb(1, 1, 1),
        borderColor: rgb(0.9, 0.9, 0.92),
        borderWidth: 1,
      });

      if (s.image) {
        try {
          const bytes = await fetchBytes(s.image);

          // try jpg first, else png
          let embedded;
          try {
            embedded = await pdf.embedJpg(bytes);
          } catch {
            embedded = await pdf.embedPng(bytes);
          }

          const dims = embedded.scale(1);
          // "cover" fit
          const scale = Math.max(imgW / dims.width, imgH / dims.height);
          const drawW = dims.width * scale;
          const drawH = dims.height * scale;

          const dx = imgX + (imgW - drawW) / 2;
          const dy = imgY + (imgH - drawH) / 2;

          page.drawImage(embedded, { x: dx, y: dy, width: drawW, height: drawH });
        } catch {
          // ignore image failures
        }
      } else {
        page.drawText("No image", {
          x: imgX + 100,
          y: imgY + 160,
          size: 16,
          font,
          color: rgb(0.55, 0.55, 0.6),
        });
      }

      // Footer
      page.drawText("Lesson Maker", {
        x: 48,
        y: 30,
        size: 12,
        font,
        color: rgb(0.45, 0.45, 0.5),
      });
    }

    const bytes = await pdf.save();
    const filename =
      (deckTitle || "lesson").replace(/[^a-z0-9-_ ]/gi, "").trim().replace(/\s+/g, "_") + ".pdf";

    return new NextResponse(Buffer.from(bytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: "export pdf failed", details: String(err?.message ?? err) },
      { status: 500 }
    );
  }
}